name: build-release
on:
  push:
    paths:
      - gradle.properties
jobs:
  job-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64
      - id: read-version
        uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: file
          version-file: gradle.properties
          version-file-extraction-pattern: '(?<=version=).+'
      - id: print-version
        run: echo "Releasing $CURRENT_VERSION"
      - id: validate-wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - id: build
        env:
          CHECKOUT_SECRET_KEY: ${{ secrets.IT_CHECKOUT_SECRET_KEY }}
          CHECKOUT_PUBLIC_KEY: ${{ secrets.IT_CHECKOUT_PUBLIC_KEY }}
          CHECKOUT_FOUR_SECRET_KEY: ${{ secrets.IT_CHECKOUT_FOUR_SECRET_KEY }}
          CHECKOUT_FOUR_PUBLIC_KEY: ${{ secrets.IT_CHECKOUT_FOUR_PUBLIC_KEY }}
        run: ./gradlew jar
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.CURRENT_VERSION }}
          release_name: ${{ env.CURRENT_VERSION }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - id: nexus-publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://e703eeff4196.ngrok.io/
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=com.checkout artifactId=checkout-sdk-java version=${{ env.CURRENT_VERSION }}
          assets: extension=jar
          filename: ./build/libs/checkout-sdk-java-${{ env.CURRENT_VERSION }}.jar